<template>
    <!-- TODO:
      - Reinstate this click handler.
      - Add a check for the imageUrl to be a valid image.
      - If not, display a placeholder image.
      - Replace the placeholder text in the popup.
      - Debug failing fonts in the modal.
    -->
    <!-- <div v-if="imageUrl" class="image-container" @click="openPopup"> -->
    <div v-if="imageUrl" class="image-container" @click="openPopup">
        <img :src="imageUrl" alt="Selected Image">
    </div>

    <!-- Popup modal -->
    <div v-if="showPopup" class="popup-overlay" @click.self="closePopup">
        <div class="popup-card">
            <div class="popup-image-container">
                <img :src="imageUrl" alt="Full Image" class="popup-image"/>
            </div>
            <div class="popup-description">

                <!-- Banner of popup description -->
                <div class="popup-description-topbar">

                    <!-- Username and time -->
                    <div class="popup-description-username">
                        <span>{{ matchingRecord.userName }}</span>
                        <span style="margin-left: 1em;">6w ago</span>
                    </div>

                    <!-- Popup close button: x -->
                    <button class="popup-close" @click="closePopup">&times;</button>
                </div>

                <div class="popup-description-content">
                    <p><strong>Notes:</strong> {{ matchingRecord.picture?.notes || "No notes available" }}</p>

                    <!-- AI Result Data -->
                    <div v-if="topPlantResult" class="ai-section">
                        <div class="ai-results-content">
                            <p><strong>Species:</strong> <span>{{ topPlantResult.species.scientificName }}</span></p>
                            <p><strong>Common Names:</strong> <span>{{ topPlantResult.species.commonNames.join(', ') }}</span></p>
                            <p><strong>Score:</strong> <span>{{ topPlantResult.score }}</span></p>
                        </div>
                        <div class="ai-results-footer">
                            <strong>Results generated by AI</strong>
                            <!-- <strong>AI INFERENCE</strong> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { defineProps, ref, computed, watchEffect } from 'vue';
import plantNetResult from '../assets/plantnet/tree1.json';

const props = defineProps({
    field: Object,
    queryResult: Array,
});

const showPopup = ref(false);
const lastImageUrl = ref(null);
const matchingRecord = ref(null);
const topPlantResult = computed(() => plantNetResult.results[0]);
// const gbifLink = computed(() => `https://www.gbif.org/species/${topPlantResult.value.gbif.id}`);


const imageUrl = computed(() => {
    if (!props.field) return lastImageUrl.value;

    const textContent = props.field.textContent || '';
    const cleanContent = textContent.trim().replace(/['"]+/g, '');

    // Now test the cleaned content
    if (cleanContent.includes('/data/') ||
        /\.(jpg|jpeg|png|webp)$/i.test(cleanContent)) {
        console.log("imageUrl computed, returning: ", cleanContent);
        return cleanContent;
    }

    console.log("imageUrl computed failed, returning: ", lastImageUrl.value);
    return lastImageUrl.value;
})

// Why do we need watchEffect?
//
// The computed blocks above can't be used to set matchingRecord.
// The only way to set matchingRecord is in a standalone watch block, or in its
// own computed block. If we use another computed block for matchingRecord
// however we will run into the problem of having to check if the clicked field
// is a url field or not, and in the case of it not being a url field,
// returning the lastMatchingRecord. We can't return null or the modal will
// stop displaying the image's details.
//
// How does this work now?
//
// If imageURL has been updated (which will only happen when the user clicks
// on  a /data/ link), also update the lastImageUrl and lastMatchingRecord
// values.
// When the user clicks on other non-url fields we want to ignore and
// continue showing the previously clicked image details.

watchEffect(() => {
  if (imageUrl.value && imageUrl.value !== lastImageUrl.value) {
    lastImageUrl.value = imageUrl.value;
    if (props.queryResult) {
        matchingRecord.value = props.queryResult.find(
            record => record.picture &&
            record.picture.imageURL === imageUrl.value
        ) || {};
    }
  }
});

function openPopup() {
    showPopup.value = true;
}

function closePopup() {
    showPopup.value = false;
    console.log("setting showPopup to: ", showPopup.value);
}

</script>

<style scoped>
.image-container {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 100%;
    overflow: hidden;
    border-radius: 8px;
    cursor: pointer;
}

img {
    max-width: 100%;
    border-radius: 8px;
}

/* Image popup
 *
 * popup-overlay: is the blurry background.
 * popup-card: is the container for both the image and the text.
 * popup-image: is the left half of popup-card, the image.
 * popup-description: is the right half of the popup-card, the text.
 */

.popup-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background: rgba(0, 0, 0, 0.6);
    display: flex;
    justify-content: center;
    align-items: center;
    backdrop-filter: blur(10px);
    z-index: 1000;
}

.popup-card {
    display: flex;
    width: 90%;
    height: 90%;
    border-radius: 15px;
    overflow: hidden;
    position: relative;
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.5);
}

.popup-image-container {
    position: relative;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    max-width: 50%;
    height: 100%;
}

.popup-image {
    object-fit: contain;
    height: auto;
    /* Reduce to 50% to get consistent borders.
     *
     * We don't know the dimension of the user uploaded images. Reducing
     * this width could avoid cropping.
     */
    width: 100%;
}


.popup-description {
    flex: 1;
    background-color: #0C0D10;
    color: white;
    padding: 2em;
    display: flex;
    flex-direction: column;
    text-align: left;
    height: 100%;
    box-sizing: border-box;
}

.popup-description-topbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    font-weight: bold;
    color: #B0B0B0;
}

.popup-description-username {
    display: inline-flex;
    align-items: center;
}

.popup-description-content {
    margin-top: 1em;
    font-size: calc(1vw + 0.5em);
    line-height: 1.5em;
    word-wrap: break-word;
    flex-grow: 1;
    overflow-y: auto;
}

.popup-description-content p {
    margin: 0;
    padding: 0;
}

.popup-close {
    position: absolute;
    top: 8px;
    right: 15px;
    z-index: 10;

    font-size: 1.5em;
    color: #B0B0B0;
    cursor: pointer;
    background: none;
    border: none;
    padding: 0;
    transition: color 0.3s ease;
    border-radius: 50%;
    display: flex;
}

.popup-close:hover {
    color: #fff;
}

/* AI results section */
.ai-section {
    padding: 1em 0.5em 0.5em 1em;
    border-radius: 8px;
    margin-top: 1em;
    font-size: calc(0.8vw + 0.5em);
    border: 1px solid #333;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.5);

    word-wrap: break-word;
    overflow-y: auto;
    font-family: "Courier New", Courier, monospace;
    text-align: left;
    font-family: monospace;
}

.ai-results-content {
    padding-left: 10px;
    padding-top: 10px;
}

.ai-results-footer {
    display: flex;
    justify-content: flex-end;
    padding-top: 10px;
}

.ai-results-footer strong {
  font-size: 10px;
  color: #ada579;
  text-align: right;
}

.ai-results-content strong {
  color: #ccc;
}

.ai-results-content span {
  color: #ada579;
}

</style>
